version: '3.7'
services:
  proxy:
    image: nginx:latest
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
    depends_on:
      - bioaps-web
      - biodoctor-web